name: Bypass Checks

on:
  issue_comment:
    types:
      - created

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/bypass checks'}}
    steps:
      - name: Bypass Checks
        uses: actions/github-script@v5
        with:
          script: |
            const {owner, repo, number} = context.issue
           
            github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });            

            
            console.log(context.sha) 

            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha: context.sha,
              state: 'success',
              context: 'test/full-test-suite/results',
              description: 'Manually bypassed',
            });
            console.log('done');

