name: Bypass Checks

on:
  issue_comment:
    types:
      - created

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/test') }}
    steps:
      - name: Bypass Checks
        uses: actions/github-script@v5
        with:
          script: |
            const {owner, repo, number} = context.issue

            github.rest.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });            

            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });     

            console.log(pr)
