name: Continuous integration

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      run: |
        cat $GITHUB_EVENT_PATH
        echo " --- "
        echo "${{ github.workflow }}"
        echo "${{ github.run_id }}"
        echo "${{ github.updated_at }}"
        echo "${{ github.event.pull_request.updated_at }}"      
        echo " --- "
        echo "${{ toJson(github) }}"      
