name: Continuous integration

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: |
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
