name: Continuous integration

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      run: |
        echo "${{ github.event.updated_at }}"
        echo "${{ github.event.pull_request.updated_at }}"      
