name: Continuous integration

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: |
          echo "${{ github.event.pull_request.head.ref || github.event.base_ref }}""
