name: Notification owner about test files timeout
on: status

jobs:
  timeout_notification:
    name: Commit Status ${{ github.event.sha }}
    runs-on: ubuntu-latest
#    if: ${{ github.event.state == 'failure' && github.event.context == '' }}
    timeout-minutes: 5
    steps:
      - name: print
        run: echo ${{ github.event.context }} = ${{ github.event.state }}
