name: Notification owner about test files timeout
on: 
  status

jobs:
  timeout_notification:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: print
        run: echo ${{ github.events.status.id }} ${{ github.events.status.name }} ${{ github.events.status.state }}
