name: Pull translations from phraseapp

on:
  schedule:
    - cron: '*/10 8-16 * * 1-5'

jobs:
  pull-translations:
    name: Pull translations from phraseapp
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check time
        id: timezone
        # Only run by 9,12,15h Paris Time
        env:
          TZ: 'Europe/Paris'
        run: |
          hour=$(date +%k)
          echo ::set-output name=skip::test "$((($hour - 9) % 3))" -eq 0 && echo "false" || echo "true"'

      - name: Checkout
        if: ${{ steps.timezone.output.skip }}
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        if: ${{ steps.timezone.output.skip }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        
      - name: Run pull_translations script
        if: ${{ steps.timezone.output.skip }}
        run: |
          bundler exec ci/release/pull_translations.rb


