name: Pull translations from phraseapp

on:
  schedule:
    - cron: '0 7-17 * * MON-FRI'

  workflow_dispatch:

jobs:
  pull-translations:
    name: Pull translations from phraseapp
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check time
        id: timezone
        # Only run by 9,12,15h Paris Time
        env:
          TZ: 'Europe/Paris'
        run: |
          echo $PATH
          hour=$(date +%k)
          if [ "${{ github.event_name }}" == "schedule" ] && [ "$((($hour - 9) % 3))" -ne 0 ]; then
            echo "skipping execution"
            echo "::set-output name=run::false"
          else
            echo "::set-output name=run::true"
          fi

      - name: Checkout
        if: ${{ steps.timezone.outputs.run }}
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        if: ${{ steps.timezone.outputs.run }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run pull_translations script
        if: ${{ steps.timezone.outputs.run }}
        run: |
          bundler exec ci/release/pull_translations.rb

      - name: Notify duty-infos channel
        if: ${{ steps.timezone.outputs.run }}
        uses: slackapi/slack-github-action@v1.14.0
        with:
          channel-id: 'duty-infos'
          slack-message: 'Update translations PR ${{ github.event.pull_request.html_url }} has been created 🚧'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
